const Recipe = [
  {
    id: 1,
    title: "Classic Tabbouleh Salad Recipe",
    img: "https://lh3.googleusercontent.com/CUOYlWWrEZA3uKXI-4-d-DWWDKPPzC8QYJyW1TB7IrOv12D0bv6uKtOckM_raZ9PtnV8I79EBGVHnz2h0OV4p1UX-Dm2wQRGYAnj",
    flag: "Premium",
    description:
      "Refreshing tabbouleh salad, loved throughout the Middle East, features loads of fresh parsley along with tomato and mint, all tossed in a tangy lemon and olive oil dressing. For the best texture, spin the parsley and mint very dry with a salad spinner (or wrap them in a kitchen towel and give them a vigorous shake); then chop them by hand, not in a food processor. You can buy fine bulgur online and at international markets, but if it’s not available, go with regular medium bulgur and soak it longer, per package directions. This is a juicy salad, and in the Middle East, the liquid from the dressing and vegetables is enjoyed along with the rest of the salad. Tabbouleh is especially good served alongside grilled meats and hummus.",
    tags: {
      nutrition: [],
      dish: [],
      course: [],
    },
    nutrition: [
      { nutrientName: "FAT_KCAL", amount: 160, unit: "kcal" },
      { nutrientName: "K", amount: 0.45, unit: "g" },
      { nutrientName: "FASAT", amount: 2.52, unit: "g" },
      { nutrientName: "FE", amount: 0, unit: "g" },
      { nutrientName: "SUGAR", amount: 2.85, unit: "g" },
      { nutrientName: "FIBTG", amount: 3.25, unit: "g" },
      { nutrientName: "PROCNT", amount: 2.75, unit: "g" },
      { nutrientName: "CHOCDF", amount: 11.98, unit: "g" },
      { nutrientName: "CHOLE", amount: 10.05, unit: "g" },
      { nutrientName: "CA", amount: 0.08, unit: "g" },
      { nutrientName: "FAT", amount: 18.47, unit: "g" },
    ],
    preparationSteps: {
      steps: [
        "Rinse bulgur in a fine mesh strainer, drain, and set aside. (This is all that’s needed to rehydrate fine bulgur, but if you’re using a coarser size, follow package directions.)",
        "Dice tomatoes and finely chop green onions. Add them (including tomato juices) to a large bowl along with parsley, mint, and salt and stir gently.",
        "Add lemon juice, olive oil, and bulgur to salad and mix well to combine.",
        "Taste salad and season with more salt, olive oil, or lemon juice if you like. If making salad ahead, chill, covered, up to 4 hours. Serve at room temperature.",
      ],
    },
  },
  {
    id: 2,
    title: "Tropical Grilled Chicken Breast",
    img: "https://lh3.googleusercontent.com/WGWTr4XZ8Gdq5FBBMM551KBW62UH9Q7c5UrDdpuSO-RdG6MRUBDBXhOU_s_ec5sz6ws1pKo0hGnpafmEwWHK91w",
    flag: "Popular On Yummly",
    description:
      "Creamy, quick, and comforting, polenta is a savory porridge that’s a starchy staple in many parts of Italy. Made from coarsely ground cornmeal, polenta is traditionally served soft with ragus, sausages, and stews, and as a side dish for roasts — basically anywhere you might serve mashed potatoes. In this version, we use a touch of milk and finish the polenta with butter and cheese to make the thrifty dish a touch more luxurious. Feel free to play with add-ins. Fresh herbs, different cheeses, and even roasted vegetables like broccoli or tomatoes are wonderful flavor boosts. You can also chill the basic polenta, cut it into sticks, and pan-fry them in olive oil in a nonstick pan; serve them with marinara sauce and a shower of Parmesan cheese for a vegetarian meal. The recipe, which makes 3 1/2 cups.",
    tags: {
      nutrition: [],
      dish: [],
      course: [],
    },
    preparationSteps: {
      steps: [
        "Put water, milk, 1 tsp. salt, and the bay leaf in a medium saucepan (about 4 qt.) and bring to a boil over high heat.",
        "Gradually whisk polenta into the pot in a slow, steady stream. This will help reduce the likelihood of lumps.",
        "Reduce heat to medium-low and simmer, reducing heat if needed so steamy bubbles rise to the surface every 5-10 seconds. Cook polenta, whisking frequently and scraping down sides of the pan, until the mixture is thick and porridge-like, 20-25 minutes. To test for doneness, carefully taste a small amount with a spoon; the mixture should be soft with a bit of texture but no grittiness. There will be a tell-tale hissing sound and a slight brown film on the bottom of the pan when the polenta is done.",
        "Remove pan from heat and discard bay leaf. Stir in butter and Parmesan, if using. Season to taste with salt and pepper.",
      ],
    },
  },
  {
    id: 3,
    title: "Cauliflower Mac & Cheese Bite",
    img: "https://lh3.googleusercontent.com/CG6Dx6Wpuzg5GbZM1nQ0RD0U3dwlCQoT4ifS4na6HZ1R_yl3JAaF6Wpra9QuiNIAC_Zy1lIVZHXeRjgwWSQ6ZAadDwg3AN_U3S8",
    flag: "Premium",
    description:
      "With this dish, you can reinvent a comfort food classic, making muffin-shaped whole grain veggie bombs and a scrumptious sauce. Sponsored by LACTAID®. LACTAID® Milk is great for cooking because it is 100% real milk, just without the lactose.",
    tags: {
      nutrition: [],
      dish: [],
      course: [],
    },
    nutrition: [
      { nutrientName: "FAT_KCAL", amount: 210, unit: "kcal" },
      { nutrientName: "K", amount: 0.13, unit: "g" },
      { nutrientName: "FASAT", amount: 19.86, unit: "g" },
      { nutrientName: "SUGAR", amount: 6.58, unit: "g" },
      { nutrientName: "FE", amount: 0, unit: "g" },
      { nutrientName: "FIBTG", amount: 2.16, unit: "g" },
      { nutrientName: "PROCNT", amount: 1.74, unit: "g" },
      { nutrientName: "CHOLE", amount: 0.06, unit: "g" },
      { nutrientName: "CA", amount: 0.02, unit: "g" },
      { nutrientName: "FAT", amount: 23, unit: "g" },
    ],
    preparationSteps: {
      steps: [
        "An introduction to Cauliflower Mac & Cheese Bites with Chef Joel, Cookie Monster, and Elmo",
        "Preheat the oven to 350°F. Line a 12-cup muffin pan with muffin liners. Set aside. Cook the pasta al dente according to package instructions. When done, strain through a colander, reserving about 1/2 cup of the pasta water for later. Run the cooked pasta under cold water, then transfer to a large bowl and set aside.",
        "Add the olive oil to a large saucepan and set over medium heat. Add the flour and cook, stirring or whisking constantly, until it is completely combined with the oil and starts to smell toasty. Carefully add one third of the milk and whisk well to combine and remove any lumps. Repeat with another third of the milk, and once the mixture is totally smooth, add the remaining third of milk and whisk to combine. Add the salt, garlic powder, and turmeric, and whisk to incorporate. Continue to cook, whisking constantly, until the mixture is totally smooth and thick enough to coat the back of a spoon.",
        "Turn the heat off under the sauce. Add the cheddar cheese and stir or whisk until smooth and combined. If the sauce is too thick, thin it by adding small amounts of the reserved pasta water. Add the cauliflower, cooked pasta, and the egg and stir into the sauce until everything is well combined and evenly coated.",
        "Using an ice cream scoop or large spoon, portion the mac and cheese into the lined muffin cups, filling them just to the top of the liners. Use spoons to top each mac and cheese bite with some of the optional toppings, customizing them as desired. Sprinkle some of the extra shredded cheddar over the top of each bite, and add a small sprinkle of chives. Bake the mac and cheese bites on middle rack of oven until they are golden brown, about 20 minutes.",
        "Check to see that mac and cheese bites are done. Remove from oven, or add time as needed.",
        "Let the mac and cheese bites cool in the pan for 5 minutes before serving.",
      ],
    },
  },
  {
    id: 4,
    title: "Dark Chocolate Coconut Bars",
    img: "https://lh3.googleusercontent.com/8rcU-nmHfVweG-JQt_QGwXRFbKv8-SQwHUu7ZuMeBPtD6cMTXN5qJ_UQRr1ObiNZaSMdMtoD7QhVs89ot9PRsQ",
    flag: "Basic",
    description:
      "Dark Chocolate Coconut Bars that are gluten-free, grain-free, dairy-free, and adhere to paleo dietary guidelines. These bars offer a decadent combination of rich dark chocolate and luscious coconut flavor. The absence of gluten and grains makes them suitable for those with dietary restrictions, while the exclusion of dairy aligns with a paleo-friendly approach. Indulge in the guilt-free pleasure of these treats, where the wholesome ingredients come together to create a satisfying and flavorful dessert or snack option.",
    tags: {
      nutrition: [],
      dish: ["Bars"],
      course: ["Desserts"],
    },
    nutrition: [
      { nutrientName: "FAT_KCAL", amount: 210, unit: "kcal" },
      { nutrientName: "K", amount: 0.13, unit: "g" },
      { nutrientName: "FASAT", amount: 19.86, unit: "g" },
      { nutrientName: "SUGAR", amount: 6.58, unit: "g" },
      { nutrientName: "FE", amount: 0, unit: "g" },
      { nutrientName: "FIBTG", amount: 2.16, unit: "g" },
      { nutrientName: "PROCNT", amount: 1.74, unit: "g" },
      { nutrientName: "CHOLE", amount: 0.06, unit: "g" },
      { nutrientName: "CA", amount: 0.02, unit: "g" },
      { nutrientName: "FAT", amount: 23, unit: "g" },
    ],
    preparationSteps: {
      steps: ["Preparation steps not available for this recipe"],
    },
  },
  {
    id: 5,
    title: "Easy All-Butter Pie Crust",
    img: "https://lh3.googleusercontent.com/J9cxHB-5nZtP6xW4MKHLNz1e-k1muY53S8JQbrGsNJGJ2lSXK8CYyb3mn_jz1iZZyVzB2jVrs54ipv8lngJ_1hNGlmPRRFiDnaM",
    flag: "Premium",
    description:
      "If you’re looking for exceptional flavor in a homemade pie crust, it’s got to be all-butter. While an all-butter crust has a reputation for being tricky, this two-crust recipe has several tricks for achieving the ultimate flaky texture as well as great flavor. Start with frozen butter (plan at least 3 hours to freeze it solid) and grate it rather than cube it so you're less likely to overwork the dough. Use ice-cold water. Minimize handling by working quickly and gently folding the dough with a rubber spatula. For a pretty presentation, before baking you can brush the top and edges of a double-crust pie crust with an egg wash of 1 large egg yolk whisked together with 2 teaspoons whole milk. It’ll create a gorgeous golden hue sure to impress. The dough will keep in the refrigerator for up to 3 days and in the freezer for up to 3 months. The recipe is a Yummly original created by [Ashley Strickland Freeman](https://www.yummly.com/dish/author/Ashley-Strickland-Freeman).",
    tags: {
      nutrition: [],
      dish: [],
      course: ["Desserts"],
    },
    nutrition: [
      { nutrientName: "FAT_KCAL", amount: 210, unit: "kcal" },
      { nutrientName: "K", amount: 0.05, unit: "g" },
      { nutrientName: "FASAT", amount: 14.47, unit: "g" },
      { nutrientName: "FE", amount: 0, unit: "g" },
      { nutrientName: "FIBTG", amount: 1.17, unit: "g" },
      { nutrientName: "PROCNT", amount: 4.19, unit: "g" },
      { nutrientName: "CHOLE", amount: 0.06, unit: "g" },
      { nutrientName: "CA", amount: 0.01, unit: "g" },
      { nutrientName: "FAT", amount: 23.37, unit: "g" },
    ],
    preparationSteps: {
      steps: [
        "In a large bowl, combine 2 1/2 cups flour and the salt. Using the large holes of a box grater, grate frozen butter onto a plate, emptying grater occasionally if needed. Or shred butter in a food processor fitted with a cold, coarse shredding disc.",
        "Add butter to flour and toss with your fingers to coat completely.",
        "Make a well in the center of the mixture and, gently folding with a rubber spatula, gradually add ice-cold water, beginning with 1/2 cup and adding additional water if needed until dough holds together without being sticky.",
        "Divide the dough into 2 discs, each about 1 inch thick. Wrap each in plastic wrap or waxed paper and refrigerate 15-30 minutes.",
        "On a lightly floured surface, roll out 1 disc into an 11-inch circle. Gently roll dough onto a rolling pin and then unroll over a 9-inch pie plate. Fit the dough into the pie plate, easing it into the inside edge without stretching.",
        "For a single-crust pie, if needed, trim edge of dough with a paring knife or kitchen scissors to an even 1-inch overhang. Fold overhang under so it’s even with the edge of the pie plate. Crimp edge of dough (pinch it gently with the thumb and index finger on one hand and press the dough in the space between those two fingers with the index finger on the other hand; repeat to crimp the entire edge). Refrigerate crust until ready to fill. Repeat to make a second single-crust pie. Fill and bake crusts as your pie recipe directs.",
        "For a double-crust pie, arrange first dough disc in pie plate as directed in Step 6 and trim, but don’t crimp the edge; refrigerate. Roll second disc into a 10-inch circle, place on a large baking sheet, and refrigerate. Fill crust in pie plate as your pie recipe directs. Gently roll dough from baking sheet onto a rolling pin and then unroll over filled crust. Trim both edges of pastry to an even 1-inch overhang. Fold dough under so it’s even with the edge of the pie plate. Crimp edge as directed in step 5, and bake as your pie recipe directs.",
      ],
    },
  },
  {
    id: 6,
    title: "Vegan Chili",
    img: "https://lh3.googleusercontent.com/4VY6fxus5iYbsXb_qBsLVFtWpcfsdj15gnNGQsskmAY3anlBnWSKVhUIcAmPw8ewJAFjtoUO-9TuQvka0UN6_w",
    flag: "Based On Your Preferences",
    description: "No description available for this recipe.",
    tags: {
      dish: ["Chili"],
    },
    nutrition: [
      { nutrientName: "FAT_KCAL", amount: 10, unit: "kcal" },
      { nutrientName: "K", amount: 1.09, unit: "g" },
      { nutrientName: "FASAT", amount: 0.01, unit: "g" },
      { nutrientName: "FE", amount: 0, unit: "g" },
      { nutrientName: "SUGAR", amount: 6.78, unit: "g" },
      { nutrientName: "FIBTG", amount: 8.06, unit: "g" },
      { nutrientName: "PROCNT", amount: 10.37, unit: "g" },
      { nutrientName: "VITA_IU", amount: 7470.75, unit: "IU" },
      { nutrientName: "CHOLE", amount: 0.11, unit: "g" },
      { nutrientName: "NA", amount: 0.49, unit: "g" },
      { nutrientName: "FAT", amount: 1.14, unit: "g" },
    ],
    preparationSteps: [
      {
        step: "Preparation steps not available for this recipe",
      },
    ],
  },
  {
    id: 7,
    title: "Red Velvet Heart Pancakes",
    img: "https://lh3.googleusercontent.com/44k3RErVqTzLnTgQW_PRfV6CmrfXxcWzP1Rp5VCrbtEq6Tcy6fqvuWVjOjpbA43vB7pybvie6qBHkEkSr3KuK49W0DTAwblmy_I",
    flag: "Premium",
    description:
      "Chef Joel's heart beets for these healthy treats! This hearty breakfast’s staple ingredients come as no surprise. Making this recipe your own is a batter of fruitful ex-berry-mentation. Sponsored by LACTAID®. LACTAID® is great for cooking because it is 100% real milk, just without the lactose and discomfort--so all members of the family can enjoy!",
    tags: {
      nutrition: [],
      dish: ["Pancakes"],
      course: [],
    },
    nutrition: [
      { nutrientName: "FAT_KCAL", amount: 150, unit: "kcal" },
      { nutrientName: "K", amount: 0.53, unit: "g" },
      { nutrientName: "FASAT", amount: 1.97, unit: "g" },
      { nutrientName: "FE", amount: 0, unit: "g" },
      { nutrientName: "SUGAR", amount: 20.52, unit: "g" },
      { nutrientName: "FIBTG", amount: 7.67, unit: "g" },
      { nutrientName: "PROCNT", amount: 14.98, unit: "g" },
      { nutrientName: "CHOCDF", amount: 71.83, unit: "g" },
      { nutrientName: "CHOLE", amount: 0.11, unit: "g" },
      { nutrientName: "CA", amount: 0.63, unit: "g" },
      { nutrientName: "FAT", amount: 17.39, unit: "g" },
    ],
    preparationSteps: {
      steps: [
        "An introduction to Red Velvet Heart Pancakes with Elmo, Cookie Monster, and Chef Joel",
        "Place the mashed beets and 1 cup of the milk in a blender and blend on high until completely smooth. Pour the mixture into a large mixing bowl and add the remaining 1 cup of milk, the honey, eggs, oil, and vanilla. Whisk well to combine.",
        "In a medium mixing bowl combine the flours, baking powder, and salt.",
        "Add the dry mixture to the wet mixture and whisk until just combined (it's ok if there are still a few small lumps). Carefully transfer the batter to a squeeze bottle, a piping bag, or large zip-top bag. If using a bag, snip about 1/4-inch from the tip for piping.",
        "Heat a large nonstick skillet or electric griddle on medium to medium-high heat. Once hot, dip a small wad of paper towel into some oil and spread a light layer over the pan or griddle. Use the squeeze bottle to draw heart-shaped pancakes onto the griddle, making sure to fill them in completely. Once the pancakes begin to form small bubbles on top, about 4 minutes, carefully flip them over. Continue cooking until lightly brown, 2-3 minutes.",
        "Transfer the pancakes to serving plates. Serve with warm maple syrup, fresh berries, and powdered sugar as desired.",
      ],
    },
  },
  {
    id: 8,
    title: "Confetti Ice Cream Sandwiches",
    img: "https://lh3.googleusercontent.com/xKF7XsBfaGvUkMrMjOPWps2sUqg3MD0op5RBKmpn2XJnNHXJ_BHWdelsDFwhbfAtd-ND18tKl8OnIeP0m5elxw_Uuiv-QFspvYM",
    flag: "Premium",
    description:
      "Sprinkles, graham crackers, and ice cream mingling with honey, strawberries, and cinna-nom-nom? It’s a party for your palate! Enjoy the leftovers for a month, unless Cookie Monster finds them. Sponsored by LACTAID®. LACTAID® Milk is 100% real milk, just without the lactose, so you can enjoy the delicious taste of milk, without the discomfort.",
    tags: {
      nutrition: [
        "Low Sugar",
        "Low Sodium",
        "Low Saturated Fat",
        "Low Fat",
        "Low Carb",
        "Low Calorie",
        "Healthy",
      ],
      dish: [],
      course: ["Desserts"],
    },
    preparationSteps: {
      steps: [
        "An introduction to Cauliflower Mac & Cheese Bites with Chef Joel, Cookie Monster, and Elmo",
        "Preheat the oven to 350°F. Line a 12-cup muffin pan with muffin liners. Set aside. Cook the pasta al dente according to package instructions. When done, strain through a colander, reserving about 1/2 cup of the pasta water for later. Run the cooked pasta under cold water, then transfer to a large bowl and set aside.",
        "Add the olive oil to a large saucepan and set over medium heat. Add the flour and cook, stirring or whisking constantly, until it is completely combined with the oil and starts to smell toasty. Carefully add one third of the milk and whisk well to combine and remove any lumps. Repeat with another third of the milk, and once the mixture is totally smooth, add the remaining third of milk and whisk to combine. Add the salt, garlic powder, and turmeric, and whisk to incorporate. Continue to cook, whisking constantly, until the mixture is totally smooth and thick enough to coat the back of a spoon.",
        "Turn the heat off under the sauce. Add the cheddar cheese and stir or whisk until smooth and combined. If the sauce is too thick, thin it by adding small amounts of the reserved pasta water. Add the cauliflower, cooked pasta, and the egg and stir into the sauce until everything is well combined and evenly coated.",
        "Using an ice cream scoop or large spoon, portion the mac and cheese into the lined muffin cups, filling them just to the top of the liners. Use spoons to top each mac and cheese bite with some of the optional toppings, customizing them as desired. Sprinkle some of the extra shredded cheddar over the top of each bite, and add a small sprinkle of chives. Bake the mac and cheese bites on middle rack of oven until they are golden brown, about 20 minutes.",
        "Check to see that mac and cheese bites are done. Remove from oven, or add time as needed.",
        "Let the mac and cheese bites cool in the pan for 5 minutes before serving.",
      ],
    },
  },
];
export default Recipe;
